name: SFUI Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
        
      - name: Install Dependencies
        run: sudo apt install -y golang npm make
        
      - name: Install Angular
        run: sudo npm install -g @angular/cli

      - name: List Dir Structure
        run: ls -la

      - name: Make UI
        run: make UI
        
      - name: Make Binary
        run: make prod
