name: SFUI Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 
        
      - name: Install Dependencies
        run: sudo apt install -y golang npm make
        
      - name: Install Angular
        run: sudo npm install -g @angular/cli

      - name: Make UI
        working-directory: ./SF-UI/
        run: make UI
        
      - name: Make Binary
        run: make prod
